### ISSUE TITLE
Автор гей 

### ISSUE THREAD

**Issue by nikusrotuslomatus** [LikoyakaTemik/VK-MIREA_gamejem#3]
вот доказательства [[https://clck.ru/anLqU])](https://clck.ru/anLqU)[https://clck.ru/anLqU](https://github.com/LikoyakaTemik/VK-MIREA_gamejem/issues/url)

**Comment by nikusrotuslomatus** [comment]
Супер гейский гей

**Comment by LikoyakaTemik** [comment]
Please, describe a problem!
